## defaults for _all_ profiles
[default]
port = 3000
address = "127.0.0.1"
limits = { form = "64 kB", json = "1 MiB" }

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }

## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 8080
secret_key = "nHYOieBdh7HfMZImqidIKXrImRJO02E8iNbQEcURgpg="

# [release.tls]
# port = 443
# certs = "/home/betty/ssl/pires_gg.ca-bundle"
# key = "/home/betty/ssl/pires_gg.p7b"