title = "Recipe for a blog"
date = "2024-03-29"
tags = ["rust", "web"]
slug = "how-to-make-a-blog"
description = """
A short post about how I made this blog using Actix, Tera, and Markdown. The small hurdles that I faced using Rust for
web development and how I should probably just use a static site generator.
"""
# Hide this page from the home page
hidden = false